### ISSUE TITLE
bug: CSV download borked from inline commas

### ISSUE THREAD

**Issue by whatrocks** [whatrocks/sqlcaster#5]
Current CSV download logic is crappy and assumes there are no commas. But many casts `text` columns have commas. I've tried different "rare" delimiters like `;` but at this point I think it may make more sense to pull in 3rd party dedicated `csv` library to just make this more robust. 

To repro, just download the default query as csv and take a peek:

https://sqlcaster.xyz/?sql=SELECT+*+FROM+casts+WHERE+username+%3C%3E+%27dwr%27+AND+reactions+IS+NOT+NULL+ORDER+BY+reactions+DESC+LIMIT+10%3B

**Comment by breck7** [comment]
https://github.com/whatrocks/sqlcaster/pull/6

**Comment by breck7** [comment]
<img width="783" alt="Screen Shot 2022-10-04 at 7 12 42 PM" src="https://user-images.githubusercontent.com/74692/193986189-66f23d88-65a3-4521-83bf-3b383dee556f.png">
