### ISSUE TITLE
feat: save + load queries to localstorage

### ISSUE THREAD

**Issue by whatrocks** [whatrocks/sqlcaster#7]
use some browser native local storage to save/load query history. if they clear their browser cache, then no worries. just a nice light storage mechanism.

can just be a dumb history at first, but probably "favorites" is another extension to consider.

**Comment by breck7** [comment]
I like this. I do it for all my sites (like https://jtree.treenotation.org/sandbox/, https://jtree.treenotation.org/designer/, https://try.scroll.pub/, et cetera).

Local storage so people dont lose work plus easy URL sharing makes for an amazing User Experience. I really like what you did with URL sharing. So simple and fast.

**Comment by whatrocks** [comment]
I've added a very basic version of this
